### PR TITLE
Test listing and loading of connections

### PR DESCRIPTION
**Pull request by RenaultAI**
Use `docker-compose` to test listing and adding of connections. In addition, add dependencies via Go modules.

### CODE REVIEW

**Comment by bronze1man** [comment]
looks like the auto test is not passed, you need pass it to submit a pr.

**Comment by RenaultAI** [comment]
Hi @bronze1man, my apologies. I was trying to add a "work in progress" label, but I wasn't able to. I'll try to fix the broken tests.

**Comment by RenaultAI** [comment]
I've updated `travis.yml` to test with `docker-compose`.

**Comment by hgl** [comment]
why go.mod points to github.com/RenaultAI/goStrongswanVici?

I fail to install this repo with go 1.11.5
```
go: github.com/bronze1man/goStrongswanVici@v0.0.0-20181105005556-92d3927c899e: parsing go.mod: unexpected module path "github.com/RenaultAI/goStrongswanVici"
```

**Pull request merged**
