### PR TITLE
Add support for rsa public keys when loading connections

### PR DESCRIPTION
**Pull request by gstroz**

### CODE REVIEW

**Comment by bronze1man** [comment]
I think you should add a field  named `PubKeyPemFilePathList` to tell the caller what he should pass in a file path of pem format, and the caller can also pass the content of PubKeys direct into it.

Please change your code ,so i can accept it.

**Comment by gstroz** [comment]
Will make changes - thanks.

**Comment by gstroz** [comment]
I still need to test this. I will let you know when it is ready.

**Comment by gstroz** [comment]
Verified this works locally with RSA keys

**Comment by gstroz** [comment]
Can be merged - it is tested

**Pull request merged**
